config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  devise_for :users
  root to: "home#index"

  post "/reservations/new", to: "reservations#new"

  resources :rooms do
    collection do
      get 'myindex'
      get 'search'
    end
  end

  resources :users
  resources :rooms
  resources :reservations
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :user
  belongs_to :room

  with_options presence: true do
    validates :check_in
    validates :check_out
    validates :people
  end

  validate :check_in_check
  validate :check_out_check

  def check_in_check
    if check_in.blank?
      return
    elsif check_in < Date.today
      errors.add(:check_in,"は今日以降の日付を選択して下さい")
    end
  end

  def check_out_check
    if check_out.blank?
      return
    elsif check_out < check_in
      errors.add(:check_out,"は開始日以降の日付を選択して下さい")
    end
  end

  def total_day_calc
    self.check_out.to_date - self.check_in.to_date
  end
end

app/models/room.rb
class Room < ApplicationRecord
  attachment :room_image
  attachment :user_image

  belongs_to :user
  has_many :reservations, dependent: :destroy

  with_options presence: true do
    validates :room_name
    validates :room_introduction
    validates :price
    validates :address
    validates :room_image
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
          :recoverable, :rememberable, :validatable

  attachment :user_image

  has_many :rooms, dependent: :destroy
  has_many :reservations, dependent: :destroy

  validates :user_name,  presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters , if: :devise_controller?
  before_action :search

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:user_name])
  end

  def search
    @q = Room.ransack(params[:q])
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @suggest_area = {"img_tokyo" => "東京", "img_osaka" => "大阪", "img_kyoto" => "京都", "img_sapporo" => "札幌"}
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController

  before_action :set_user, only: [:destroy]
  before_action :set_reservation, only: [:show, :destroy]
  before_action :set_room, only: [:new, :create]


  def index
    @reservations = current_user.reservations.all.order(:check_in)
  end

  def new
    @reservation = Reservation.new(reservation_params)
    @reservation.user_id = current_user.id
    if @reservation.invalid?
      render 'rooms/show'
    else
      @reservation.total_day = @reservation.total_day_calc.to_i
      @reservation.total_price = @room.price * @reservation.people * @reservation.total_day
      #binding.pry
    end
  end

  def create
    @reservation = Reservation.new(reservation_params)
    if @reservation.save
      flash[:notice] = "予約が完了しました"
      redirect_to reservation_path(@reservation)
    else
      params[:back] || !@reservation.save || @reservation.invalid?
      render 'rooms/show'
      flash[:notice] ="予約が出来ませんでした"
    end
  end

  def show
  end

  def destroy
    if @reservation.check_in < Date.today
      flash[:notice] = "キャンセル可能日を過ぎています"
      return
    else
      @reservation.destroy
      redirect_to reservations_path(@reservation)
      flash[:notice] = "予約をキャンセルしました"
    end
  end

  private

  def reservation_params
    params.require(:reservation).permit(:check_in, :check_out, :people, :total_day, :total_price, :user_id, :room_id)
  end

  def set_user
    @reservation = Reservation.find(params[:id])
    if @reservation.user_id != current_user.id
      flash[:alert] = "キャンセル出来ません"
      return
    end
  end

  def set_reservation
    @reservation = Reservation.find(params[:id])
  end

  def set_room
    @room = Room.find(params[:reservation][:room_id])
  end

end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_q

  def index
    @rooms = Room.all
  end

  def myindex
    @rooms = current_user.rooms.all
  end

  def new
    @room = Room.new
  end

  def create
    @room = Room.new(room_params)
    @room.user_id = current_user.id
    if @room.save
      flash[:notice] = "ルームを登録しました"
      redirect_to rooms_path
    else
      flash[:notice] = "ルームの登録が出来ませんでした"
      render "new"
    end
  end

  def show
    @room = Room.find(params[:id])
    @reservation = Reservation.new
    #binding.pry
  end

  def search
    @q = Room.ransack(params[:q])
    @rooms = @q.result(distinct: true)
  end

  private

  def room_params
    params.require(:room).permit(:room_name, :room_introduction, :price, :address, :room_image).merge(user_id: current_user.id)
  end

  def set_q
    @q = Room.ransack(params[:q])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :set_user, only: [:show, :edit, :update]
  before_action :check_user, only: [:edit, :update]

  def index
    @users = User.all
  end

  def show
  end

  def edit
  end

  def update
    if @user.update(user_params)
      flash[:notice] = "ユーザー情報を更新しました"
      redirect_to edit_user_path(@user)
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:user_name, :email, :user_image, :user_introduction)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def check_user
    if @user != current_user
      flash[:notice] = "不正なアクセスです"
      redireft_to root_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<section class="hero is-halfheight mb-6" style="background-image: url('https://presite-potepancamp-rails-02.herokuapp.com/assets/img_cover_top.jpg')">
  <div class="hero-body">
    <div class="container">
      <form class="box">
        <p class="title">Potepan Shareでまだ体験したことのない旅をしよう</p>

        <p class="label">エリア</p>
          <%= search_form_for @q, url: search_rooms_path do |f| %>
            <%= f.search_field :address_cont, placeholder: "東京", id:"top-search"%><br>
            <%= f.submit "探す", id:"top-submit" %>
          <% end %>
      </form>
    </div>
  </div>
</section>

<section class="section mx-6 px-2 py-0">
  <h1 class="title is-4 px-6">おすすめのエリア</h1>

  <div class="columns has-text-centered mb-3 px-6">
    <% @suggest_area.each do |key, value| %>
      <div class="column is-3">
        <span class="is-size-5"><%= value %></span>
        <%= link_to image_tag("#{key}.jpeg", class:"picture"), search_rooms_path(q: {address_cont: "#{value}"}), class:"image is-4by5 mt-1" %>
      </div>
    <% end %>
  </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Poteshare</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.4/css/all.css">
  </head>

  <body>
    <% if flash[:notice] %>
      <div class="notification is-primary mb-0">
        <p class="notice"><%= notice %></p>
      </div>
    <% end %>

    <% if flash[:alert] %>
      <div class="notification is-warning mb-0"></div>
        <p class="alert"><%= alert %></p>
    <% end %>

    <nav class="navbar is-small is-black p-2" role="navigation" aria-label="main navigation">
      <div class="navbar-brand">
        <a href="/" class="navbar-item">
          <img src="https://presite-potepancamp-rails-02.herokuapp.com/assets/logo.png" alt="サイトのロゴ画像">
        </a>
        <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="top-menu">
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
        </a>
      </div>


      <div class="navbar-menu" id="top-menu" >
        <div class="navbar-start">
          <%= search_form_for @q, url: search_rooms_path, class: "navbar-item pr-0" do |f| %>
            <%= f.search_field :address_cont, placeholder: "エリア" %>
          <% end %>
          <%= search_form_for @q, url: search_rooms_path, class: "navbar-item" do |f| %>
            <%= f.search_field :room_name_or_address_or_room_introduction_cont, placeholder: "キーワード" %>
          <% end %>
        </div>
      </div>

      <% if user_signed_in? %>
      <div class="navber-end my-auto">
        <div class="navbar-item" id="list">
          <div class="field is-grouped">
            <div class="navbar-item has-dropdown is-hoverable">
              <p class="navbar-link mx-2"><%= current_user.user_name %></p>
              <ul class="navbar-dropdown p-2 mt-1">
                <a><li class="navbar-item p-2"><%= link_to "ルーム登録", new_room_path %></li></a>
                <a><li class="navbar-item p-2"><%= link_to "ルーム一覧", rooms_path %></li></a>
                <a><li class="navbar-item p-2"><%= link_to "予約済みルーム一覧", reservations_path %></li></a>
                <a><li class="navbar-item p-2"><%= link_to "マイページ", user_path(current_user.id) %></li></a>
                <a><li class="navbar-item p-2"><%= link_to "ログアウト", destroy_user_session_path, method: :delete	%></li></a>
              </ul>
            </div>
            <figure class="image">
              <%= attachment_image_tag @user, :user_image, fallback: "default_icon.jpeg", class:"image is-48x48" %>
            </figure>
          </div>
        </div>
      <% else %>
      <div class="navbar-end is-align-items-center mr-5">
        <div class="barvar-item">
          <div class="field is-grouped">
            <p class="control">
              <%= link_to "ログイン", new_user_session_path, class: "button is-link is-link"	%>
            </p>
            <p class="control">
              <%= link_to "新規登録", new_user_registration_path, class: "button is-light is-grey" %>
            </p>
          </div>
        </div>
      </div>
      <% end %>
    </nav>

    <%= yield %>

    <footer class="footer has-background-black has-text-white">
      <div class="content has-text-centered">
        <p>© 2020 POTEPAN.INC.</p>
      </div>
    </footer>

  </body>
</html>

app/views/reservations/index.html.erb
<h1 class="title is-4 m-6">予約済みルーム一覧</h1>

<table class="table is-striped m-6">
  <thead class="has-text-centered">
    <tr>
      <th>ルーム画像</th>
      <th>ルーム名</th>
      <th>ルーム紹介</th>
      <th>合計金額</th>
      <th>開始日</th>
      <th>終了日</th>
      <th>予約確定日時</th>
      <th>予約キャンセル</th>
    </tr>
  </thead>

  <tbody>
    <% @reservations.each do |reservation| %>
      <tr>
        <td><%= attachment_image_tag reservation.room, :room_image, size: "240x120" %></td>
        <td class="is-underlined has-text-weight-bold"><%= link_to reservation.room.room_name, room_path(reservation.room_id) %></td>
        <td><%= reservation.room.room_introduction %></td>
        <td><%= reservation.total_price %>円</td>
        <td><%= reservation.check_in.to_s(:datetime_jp) %></td>
        <td><%= reservation.check_out.to_s(:datetime_jp) %></td>
        <td><%= reservation.created_at.to_s(:datetime_jp) %></td>
        <% if reservation.user_id == current_user.id %>
          <td class="has-text-weight-bold"><%= link_to "キャンセル", reservation, method: :delete, data: { confirm: "本当にキャンセルしますか?" }, class:"has-text-danger" %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/reservations/new.html.erb
<div class="box mx-auto mt-6">
  <h1 class="title is-4" id="content-border">予約内容確認</h1>

  <%= render "shared/error", obj:@reservation %>

  <div class="field">
    <div class="label">
      <p>¥<span><%= @reservation.room.price %></span>/日</p>
    </div>
  </div>

  <%= form_with model: @reservation do |f| %>
    <%= f.hidden_field :user_id, value: current_user.id %>
    <%= f.hidden_field :room_id, value: @room.id %>
    <div class="field">
      <div class="label">
        <%= f.label :check_in, "開始日" %>
      </div>
        <%= f.date_field :check_in, :readonly => true, id:"reservation-field" %>
    </div>

    <div class="field">
      <div class="label">
        <%= f.label :check_out, "終了日" %>
      </div>
        <%= f.date_field :check_out, :readonly => true, id:"reservation-field" %>
    </div>

    <div class="field" id="content-border">
      <div class="label">
        <p>使用日数 : <%= @reservation.total_day %> 日</p>
      </div>
    </div>

    <div class="field" id="content-border">
      <div class="label">
        <%= f.label :check_out, "人数（人）" %>
      </div>
        <%= f.number_field :people, :readonly => true, id:"reservation-field" %>
    </div>

    <div class="field">
      <div class="label">
        <%= f.label :total_price, "合計金額（円）" %>
      </div>
        <%= f.number_field :total_price, :readonly => true, id:"reservation-field" %>
    </div>

    <p class="mt-4 is-size-7" id="content-border">上記内容で宜しければ「予約確定」を押して下さい</p>

    <div class="mb-3">
      <%= f.submit "予約確定", class:"button is-link px-6 mt-3", id:"submit" %><br>
      <%= f.submit "戻る", name: :back, class:"button has-background-grey has-text-white px-6 mt-3", id:"submit" %>
    </div>
  <% end %>
</div>

app/views/reservations/show.html.erb
<div class="box mx-auto mt-6">
  <h1 class="title is-4">予約完了</h1>

  <table class="table is-striped mx-auto" style="width: 100%;">
    <tr>
      <th>予約したお部屋</th>
      <td class="has-text-left"><%= @reservation.room.room_name %></td>
    </tr>
    <tr>
      <th>開始日</th>
      <td class="has-text-left"><%= @reservation.check_in.to_s(:datetime_jp) %></td>
    </tr>
    <tr>
      <th>終了日</th>
      <td class="has-text-left"><%= @reservation.check_out.to_s(:datetime_jp) %></td>
    </tr>
    <tr>
      <th>金額</th>
      <td class="has-text-left"><%= @reservation.total_price %>円</td>
    </tr>
  </table>

  <div>
    <ul>
      <li><%= link_to "予約一覧に戻る", reservations_path, class:"button is-link px-6 mt-3" %></li>
    </ul>
  </div>
</div>

app/views/rooms/index.html.erb
<h1 class="title is-4 m-6">ルーム一覧</h1>

<table class="table is-striped m-6">
  <thead class="has-text-centered">
    <tr>
      <th>ルーム画像</th>
      <th>ルーム名</th>
      <th>ルーム紹介</th>
      <th>料金</th>
      <th>作成日</th>
    </tr>
  </thead>

  <tbody>
    <% @rooms.each do |room| %>
      <tr>
        <td><%= attachment_image_tag room, :room_image, size: "240x120" %></td>
        <td class="is-underlined has-text-weight-bold"><%= link_to room.room_name, room_path(room) %></td>
        <td><%= room.room_introduction %></td>
        <td><%= room.price %>円</td>
        <td><%= room.created_at.to_s(:datetime_jp) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/rooms/myindex.html.erb
<h1 class="title is-4 m-6">登録済みルーム一覧</h1>

<table class="table is-striped m-6">
  <thead class="has-text-centered">
    <tr>
      <th>ルーム画像</th>
      <th>ルーム名</th>
      <th>ルーム紹介</th>
      <th>料金</th>
      <th>作成日</th>
    </tr>
  </thead>

  <tbody>
    <% @rooms.each do |room| %>
      <tr>
        <td><%= attachment_image_tag room, :room_image, size: "240x120" %></td>
        <td class="is-underlined has-text-weight-bold"><%= link_to room.room_name, room_path(room) %></td>
        <td><%= room.room_introduction %></td>
        <td><%= room.price %></td>
        <td><%= room.created_at.to_s(:datetime_jp) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<div>
  <ul>
    <li class="button ml-6 mb-6 is-link"><%= link_to "マイページへ戻る", user_path(current_user.id), class:"has-text-white" %></li>
  </ul>
</div>

app/views/rooms/new.html.erb
<div clas="tile is-ancestor" id="tile">
  <div class="tile">
    <div class="tile is-parent is-2">
      <div class="tile is-child notification is-primary">
        <p class="menu-label is-hidden-touch has-text-black">メニュー</p>
          <ul class="menu-list">
            <li class="mb-2"><%= link_to "基本情報", new_room_path %></li>
          </ul>
      </div>
    </div>

    <div class="tile is-parent is-8">
      <div class="tile is-child notification">
        <h1 class="title is-4">ルーム情報登録</h1>

        <%= render "shared/error", obj: @room %>

        <%= form_with model: @room do |f| %>
          <div class="field is-horizontal">
            <table>
              <tr>
                <th class="label"><%= f.label :room_name, "ルーム名" %><span class="tag is-danger ml-3">必須</span></th>
                <th class="field"><%= f.text_field :room_name, placeholder: "ルーム名を入力して下さい", class:"input mb-3", type:"text" %></th>
              </tr>
              <tr>
                <th class="label"><%= f.label :room_introduction, "ルーム紹介" %><span class="tag is-danger ml-3">必須</span></th>
                <th><%= f.text_area :room_introduction, placeholder: "ルーム説明を入力して下さい", class:"textarea mb-3" %></th>
              </tr>
              <tr>
                <th class="label"><%= f.label :price, "料金" %><span class="tag is-danger ml-3">必須</span></th>
                <th><%= f.text_field :price, placeholder: "1日あたりの料金を入力して下さい", class:"input mb-3", type:"text" %></th>
              </tr>
              <tr>
                <th class="label"><%= f.label :address, "住所" %><span class="tag is-danger ml-3">必須</span></th>
                <th><%= f.text_field :address, placeholder: "を住所を入力して下さい", class:"input mb-3", type:"text" %></th>
              </tr>
              <tr>
                <th class="label mr-6"><%= f.label :room_image, "ルーム画像 "%><span class="tag is-danger ml-3">必須</span></th>
                <th><%= f.attachment_field :room_image, class:"file mb-3" %></th>
              </tr>
            </table>
          </div>
          <ul>
            <li><%= f.submit "登録" ,class:"button is-link mr-3" %></li>
          </ul>

        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/rooms/search.html.erb
<h1 class="title is-4 m-6">検索結果 : <%= @rooms.count %> 件</h1>

<div class="columns is-multiline m-6">
  <% if @rooms.present? %>
    <% @rooms.each do |room| %>
      <div class="column is-3">
        <div class="card">

          <div class="card-image">
            <%= link_to room_path(room) do %>
              <%= attachment_image_tag room, :room_image, size: "413x180" %>
            <% end %>
          </div>

          <div class="card-content p-4">
            <div class="content mb-3 has-text-weight-bold">
              <%= link_to room.room_name, room_path(room) %>
            </div>
            <div class="content mb-3 has-text-weight-bold">
              <%= link_to room.address, room_path(room), class:"has-text-black" %>
            </div>
            <div class="content has-text-right">
              <p>¥<%= link_to room.price, room_path(room), class:"has-text-black" %>-</p>
            </div>
          </div>

        </div>
      </div>
    <% end %>
  <% else %>
    <p>検索結果が有りませんでした</p>
  <% end %>

</div>

app/views/rooms/show.html.erb
<%= render "shared/error", obj:@reservation %>

<h1 class="title is-4 m-6">ルーム情報詳細</h1>

<div class="columns is-centered m-6">
  <div class="column is-7">
    <div class="card">
      <div class="card-image">
        <figure class="image is-2by1">
          <%= attachment_image_tag @room, :room_image %></p>
        </figure>
      </div>

      <div class="card-content">
        <div class="media">
          <figure class="media-left mr-5 my-auto">
            <p><%= attachment_image_tag current_user, :user_image, fallback: "default_icon.jpeg", class:"image is-48x48" %></p>
          </figure>
          <div class="medlia-content">
            <p class="has-text-weight-bold is-size-4"><%= @room.room_name %></p>
            <p class="mt-3"><%= @room.address %></p>
          </div>
        </div>
      </div>

      <div class="card-footer py-6 pl-5">
        <p><%= @room.room_introduction %></p>
      </div>
    </div>
  </div>

  <div class="box mt-3 mx-4 p-6" style="width:100%">
    <p class="is-size-4 mb-3">¥<span><%= @room.price %></span>/日</p>

    <%= form_with model: @reservation, url: new_reservation_path, local: true do |f| %>
      <%= f.hidden_field :room_id, value: @room.id %>

      <div class="field">
        <div class="label">
          <%= f.label :check_in,"開始日" %>
        </div>
          <%= f.date_field :check_in, id:"field" %>
      </div>

      <div class="field">
        <div class="label">
          <%= f.label :check_out,"終了日" %>
        </div>
          <%= f.date_field :check_out, id:"field" %>
      </div>

      <div class="field">
        <div class="label">
          <%= f.label :people,"人数" %>
        </div>
        <%= f.text_field :people, id:"field" %>
      </div>

      <div class="has-text-centered">
        <% if user_signed_in? %>
          <%= f.submit "予約する", class:"button is-link px-6 mt-3" %>
        <% else %>
          <%= link_to "ログイン", new_user_session_path, class:"button is-link px-6 mt-3" %>
        <% end %>
      </div>
    <% end %>
  </div>

</div>

app/views/shared/_error.html.erb
<% if obj.errors.any? %>
  <% obj.errors.full_messages.each do |message| %>
    <ul>
      <li class="has-text-danger has-text-weight-bold"><span>※ </span><%= message %></li>
    </ul>
  <% end %>
<% end %>

app/views/shared/_side.html.erb
  <div class="tile is-parent is-2">
      <div class="tile is-child notification is-primary">
        <p class="menu-label is-hidden-touch has-text-black">メニュー</p>
          <ul class="menu-list">
            <li class="mb-2"><%= link_to "アカウント", user_path(@user) %></li>
            <li class="mb-2"><%= link_to "プロフィール", edit_user_path(@user) %></li>
            <li class="mb-2"><%= link_to "登録済みルーム一覧", myindex_rooms_path(current_user.id)	%></li>
          </ul>
      </div>
    </div>

app/views/users/edit.html.erb
<div clas="tile is-ancestor" id="tile">
  <div class="tile">

    <%= render "shared/side" %>

    <div class="tile is-parent is-8">
      <div class="tile is-child notification">
        <h1 class="title is-4">プロフィール</h1>
        <%= form_with model:@user do |f| %>

          <div class="field is-horizontal">
            <table>
              <figure class="image">
                <th><%= attachment_image_tag @user, :user_image, fallback: "default_icon.jpeg", class:"image is-48x48 mb-3 ml-5"%></th>
              </figure>

              <tr>
                <th class="label mr-6">アイコン画像<span class="tag is-danger ml-3">必須</span></th>
                <td class="field"><%= f.attachment_field :user_image, class:"file mb-3" %></td>
              </tr>
              <tr>
                <th class="label">名前<span class="tag is-danger ml-3">必須</span></th>
                <td class="field"><%= f.text_field :user_name, class:"input mb-3", type:"text" %></td>
              </tr>
              <tr>
                <th class="label">自己紹介<span class="tag is-danger ml-3">必須</span></th>
                <td class="field"><%= f.text_area :user_introduction, class:"textarea mb-3"%></td>
              </tr>
            </table>
          </div>

          <div>
            <ul class="buttons">
              <li><%= f.submit "更新", class:"button is-link mr-3" %></li>
              <li class="button"><%= link_to "ホームへ戻る", root_path %></li>
            </ul>
          </div>

        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div clas="tile is-ancestor" id="tile">
  <div class="tile">

    <%= render "shared/side" %>

    <div class="tile is-parent is-8">
      <div class="tile is-child notification">
        <h1 class="title is-4">アカウント</h1>

        <div class="field is-horizontal">
          <table>
            <tr>
              <th class="label">名前</th>
              <td class="field has-text-left"><%= @user.user_name %></td>
            </tr>
            <tr>
              <th class="label mr-6">メールアドレス</th>
              <td class="field has-text-left"><%= @user.email %></td>
            </tr>
            <tr>
              <th class="label">パスワード</th>
              <td class="field has-text-left">*********</td>
            </tr>
          </table>
        </div>

        <div>
          <ul class="buttons">
            <li class="button is-link"><%= link_to "編集", edit_user_registration_path %></li>
            <li class="button"><%= link_to "ホームへ戻る", root_path %></li>
          </ul>
        </div>

      </div>
    </div>
  </div>
</div>